In [1]:
import numpy as np
a= np.array([10,20,30,40,50])
print(a)
print(a.size)


[10 20 30 40 50]
5


In [10]:
a= np.array([10,20,30,40,50])
print((a+5)*a)
print(np.sqrt(a))

print(np.std(a))
print(np.mean(a))



a.sum()
a.std()
a.mean()


[ 150  500 1050 1800 2750]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
14.142135623730951
30.0


np.float64(30.0)